version: '3.1'

services:
  db:
    container_name: tastee_db
    image: postgres:12.6
    restart: always
    environment:
      POSTGRES_DB: tastee_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - 8432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus:v2.26.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:7.5.6
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus


volumes:
  grafana-data:
  prometheus-data:
  db-data:
