version: '3.1'

services:
  db:
    container_name: tastee_db
    image: postgres:12.6
    restart: always
    environment:
      POSTGRES_DB: tastee_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - 8432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.26.1
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml

volumes:
  db-data:
  prometheus-data:

